name: CI

on:
  push:
    branches:
      - master
      - dev
      - prod
  pull_request:
    branches:
      - master
      - dev
      - prod

permissions:
  checks: write
  contents: write

jobs:
  format:
    name: Format
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Set up pnpm
        uses: pnpm/action-setup@v4

      - name: Install Node.js dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Check formatting
        run: pnpm run format

  typecheck:
    name: Typecheck
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Set up pnpm
        uses: pnpm/action-setup@v4

      - name: Install Node.js dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Typecheck
        run: pnpm run typecheck

  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Set up pnpm
        uses: pnpm/action-setup@v4

      - name: Install Node.js dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Lint
        run: pnpm run lint
